spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        ddl-auto: create
      dialect: org.hibernate.dialect.MySQL8InnoDBDialect
    defer-datasource-initialization: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hobiday?serverTimezone=UTC
#    url: jdbc:mysql://localhost:{????}/{?????? ??}?serverTimezone=UTC
    username: root
    password: 95206326
#    password: { root password }
  h2:
    console:
      enabled: true
  security:
    oauth2:
      client:
        provider: # kakao and naver login need this provider (not Google, Facebook)
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
        registration:
          kakao:
            client-id: f50d9911e72a37532cae75cba2277099
            client-secret: FxIHbsanlyYyDot1yzsoaMS1y0T7fFgi
            client-authentication-method: client_secret_post
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-name: kakao
            scope:
              - profile_nickname
              - account_email
#              - profile_image
# https://developers.kakao.com/docs/latest/ko/kakaologin/rest-api#kakaologin
jwt:
  issuer: chyun5197@gmail.com
  secret_key: team8-project